# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hashmatch < Formula
  desc "A simple cli tool to generate file hashes and match them."
  homepage ""
  version "0.0.6"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agrimrules/hashmatch/releases/download/v0.0.6/hashmatch_0.0.6_Darwin_x86_64.tar.gz"
      sha256 "846e428b42a39b970aafa2981ca9b5ae488ca54cdd63bb9123a38e01d4ca8b6f"
    end
    if Hardware::CPU.arm?
      url "https://github.com/agrimrules/hashmatch/releases/download/v0.0.6/hashmatch_0.0.6_Darwin_arm64.tar.gz"
      sha256 "07e060ccc8145599c1a55a55a1ce7c991d1a43e3728c428430dba656a75c3260"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/agrimrules/hashmatch/releases/download/v0.0.6/hashmatch_0.0.6_Linux_x86_64.tar.gz"
      sha256 "190fa7c9fff1ce0b61cc563b144c693fffe106d78fc19e643b4538b099275ed8"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agrimrules/hashmatch/releases/download/v0.0.6/hashmatch_0.0.6_Linux_arm64.tar.gz"
      sha256 "9eee77d8adb13fbbbb1cb9971b1f1c10f3d81fb4e4ee363668588f361b2d0e50"
    end
  end

  def install
    bin.install "hashmatch"
  end

  test do
    system "hashmatch -v"
  end
end
