# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hashmatch < Formula
  desc "A simple cli tool to generate file hashes and match them."
  homepage ""
  version "0.0.5"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agrimrules/hashmatch/releases/download/v0.0.5/hashmatch_0.0.5_Darwin_x86_64.tar.gz"
      sha256 "bd1e3fbee99bd726501c5e3eada795617ae84fddda02d66c487c94514bfad477"
    end
    if Hardware::CPU.arm?
      url "https://github.com/agrimrules/hashmatch/releases/download/v0.0.5/hashmatch_0.0.5_Darwin_arm64.tar.gz"
      sha256 "d77a343080ec6e6c4a14857219b2d4f14655e5eb60b041b7f59567361632be49"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/agrimrules/hashmatch/releases/download/v0.0.5/hashmatch_0.0.5_Linux_x86_64.tar.gz"
      sha256 "65d54d67986accb7e5b9eef498980e3757b5734d381d7bfba75a86e275a8684d"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agrimrules/hashmatch/releases/download/v0.0.5/hashmatch_0.0.5_Linux_arm64.tar.gz"
      sha256 "7a7b08921c522f5aef56de45dd9fce628cd7c0e0f6120cc941082b35c59ba66e"
    end
  end

  def install
    bin.install "hashmatch"
  end

  test do
    system "hashmatch -v"
  end
end
