# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hashmatch < Formula
  desc "A simple cli tool to generate file hashes and match them."
  homepage ""
  version "0.0.7"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agrimrules/hashmatch/releases/download/v0.0.7/hashmatch_0.0.7_Darwin_x86_64.tar.gz"
      sha256 "5723b8dbcb899bfdb6c50ee1a578424b82f2cb07348ce9e0af8bf37f8bd3fcd1"
    end
    if Hardware::CPU.arm?
      url "https://github.com/agrimrules/hashmatch/releases/download/v0.0.7/hashmatch_0.0.7_Darwin_arm64.tar.gz"
      sha256 "18ee2008482d8254db9c6078cc027feb5134c4ae945bf72ef19cc2de5daa364f"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/agrimrules/hashmatch/releases/download/v0.0.7/hashmatch_0.0.7_Linux_x86_64.tar.gz"
      sha256 "0020707afc48e8449234aeed168db7b70e8dc17e185331b5cf449d25fbf43eef"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agrimrules/hashmatch/releases/download/v0.0.7/hashmatch_0.0.7_Linux_arm64.tar.gz"
      sha256 "e521d6df213c924493d5a0ddbb22fa4833feb9c34eb08f8825e58c8683e641c7"
    end
  end

  def install
    bin.install "hashmatch"
  end

  test do
    system "hashmatch -v"
  end
end
